// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0cgkRKLPxpaSQ0ZTnMYFg6JkCIoL-kxE',
    appId: '1:445586647341:web:985e7f27a41c78e5158ba4',
    messagingSenderId: '445586647341',
    projectId: 'dima-eshopping',
    authDomain: 'dima-eshopping.firebaseapp.com',
    databaseURL: 'https://dima-eshopping-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'dima-eshopping.appspot.com',
    measurementId: 'G-LVHJ90E8C2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUlr2nMn4zsSdw7YY8sqg0mU32XWsnlm4',
    appId: '1:445586647341:android:d5267947830f3125158ba4',
    messagingSenderId: '445586647341',
    projectId: 'dima-eshopping',
    databaseURL: 'https://dima-eshopping-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'dima-eshopping.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPU9r3nWcXMxWkHkXdg1zxa72NKkZIZME',
    appId: '1:445586647341:ios:6004d7c1da11cd33158ba4',
    messagingSenderId: '445586647341',
    projectId: 'dima-eshopping',
    databaseURL: 'https://dima-eshopping-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'dima-eshopping.appspot.com',
    iosClientId: '445586647341-m3hienpnpcl67dnjcl8reag0c7vu6joj.apps.googleusercontent.com',
    iosBundleId: 'com.example.dima',
  );
}
